### PR TITLE
Python 3 support (closes #34)

### LINKED ISSUE #34: Python 3 support
Reticketed from #10, because I am not able to contact people from Google Code. If you're about to submit pull request, make sure to uncomment Python 3 lines in https://github.com/techtonik/python-patch/blob/master/.travis.yml

Where is this needed:
* https://github.com/conda/conda-build/issues/498
* https://github.com/conda/conda-build/issues/119

### PR DESCRIPTION
**Pull request by yan12125**
I start this work from scratch. None of previous patches are used.

### CODE REVIEW

**Comment by yan12125** [comment]
Great! All tests passed https://travis-ci.org/techtonik/python-patch/builds/103869201.

**Comment by techtonik** [comment]
Wow. Thanks.

It is a pity that we text file need to be treated as binary. I need some time to think about that, but on the first glimpse it looks like there is no other choice.

**Comment by techtonik** [comment]
Thanks. I merged it, because it works. =) Better do post-review.

**Comment by techtonik** [comment]
Done. https://pypi.python.org/pypi/patch/1.16

**Pull request merged**
